eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/notificationdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update